/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as storecreateImport } from './routes/store/create'
import { Route as authlayoutImport } from './routes/auth/layout'
import { Route as indexImport } from './routes/index'
import { Route as authsignUpImport } from './routes/auth/sign-up'
import { Route as authsignInImport } from './routes/auth/sign-in'
import { Route as storedashboardImport } from './routes/store/dashboard'
import { Route as storedashboardIndexImport } from './routes/store/dashboard-index'

// Create/Update Routes

const storecreateRoute = storecreateImport.update({
  path: '/create-store',
  getParentRoute: () => rootRoute,
} as any)

const authlayoutRoute = authlayoutImport.update({
  id: '/_auth-layout-id',
  getParentRoute: () => rootRoute,
} as any)

const indexRoute = indexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authsignUpRoute = authsignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => authlayoutRoute,
} as any)

const authsignInRoute = authsignInImport.update({
  path: '/sign-in',
  getParentRoute: () => authlayoutRoute,
} as any)

const storedashboardRoute = storedashboardImport.update({
  path: '/store/$storeId/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const storedashboardIndexRoute = storedashboardIndexImport.update({
  path: '/',
  getParentRoute: () => storedashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout-id': {
      id: '/_auth-layout-id'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authlayoutImport
      parentRoute: typeof rootRoute
    }
    '/create-store': {
      id: '/create-store'
      path: '/create-store'
      fullPath: '/create-store'
      preLoaderRoute: typeof storecreateImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout-id/sign-in': {
      id: '/_auth-layout-id/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authsignInImport
      parentRoute: typeof authlayoutImport
    }
    '/_auth-layout-id/sign-up': {
      id: '/_auth-layout-id/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authsignUpImport
      parentRoute: typeof authlayoutImport
    }
    '/store/$storeId/dashboard': {
      id: '/store/$storeId/dashboard'
      path: '/store/$storeId/dashboard'
      fullPath: '/store/$storeId/dashboard'
      preLoaderRoute: typeof storedashboardImport
      parentRoute: typeof rootRoute
    }
    '/store/$storeId/dashboard/': {
      id: '/store/$storeId/dashboard/'
      path: '/'
      fullPath: '/store/$storeId/dashboard/'
      preLoaderRoute: typeof storedashboardIndexImport
      parentRoute: typeof storedashboardImport
    }
  }
}

// Create and export the route tree

interface authlayoutRouteChildren {
  authsignInRoute: typeof authsignInRoute
  authsignUpRoute: typeof authsignUpRoute
}

const authlayoutRouteChildren: authlayoutRouteChildren = {
  authsignInRoute: authsignInRoute,
  authsignUpRoute: authsignUpRoute,
}

const authlayoutRouteWithChildren = authlayoutRoute._addFileChildren(
  authlayoutRouteChildren,
)

interface storedashboardRouteChildren {
  storedashboardIndexRoute: typeof storedashboardIndexRoute
}

const storedashboardRouteChildren: storedashboardRouteChildren = {
  storedashboardIndexRoute: storedashboardIndexRoute,
}

const storedashboardRouteWithChildren = storedashboardRoute._addFileChildren(
  storedashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '': typeof authlayoutRouteWithChildren
  '/create-store': typeof storecreateRoute
  '/sign-in': typeof authsignInRoute
  '/sign-up': typeof authsignUpRoute
  '/store/$storeId/dashboard': typeof storedashboardRouteWithChildren
  '/store/$storeId/dashboard/': typeof storedashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof indexRoute
  '': typeof authlayoutRouteWithChildren
  '/create-store': typeof storecreateRoute
  '/sign-in': typeof authsignInRoute
  '/sign-up': typeof authsignUpRoute
  '/store/$storeId/dashboard': typeof storedashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof indexRoute
  '/_auth-layout-id': typeof authlayoutRouteWithChildren
  '/create-store': typeof storecreateRoute
  '/_auth-layout-id/sign-in': typeof authsignInRoute
  '/_auth-layout-id/sign-up': typeof authsignUpRoute
  '/store/$storeId/dashboard': typeof storedashboardRouteWithChildren
  '/store/$storeId/dashboard/': typeof storedashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/create-store'
    | '/sign-in'
    | '/sign-up'
    | '/store/$storeId/dashboard'
    | '/store/$storeId/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/create-store'
    | '/sign-in'
    | '/sign-up'
    | '/store/$storeId/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_auth-layout-id'
    | '/create-store'
    | '/_auth-layout-id/sign-in'
    | '/_auth-layout-id/sign-up'
    | '/store/$storeId/dashboard'
    | '/store/$storeId/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  authlayoutRoute: typeof authlayoutRouteWithChildren
  storecreateRoute: typeof storecreateRoute
  storedashboardRoute: typeof storedashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  authlayoutRoute: authlayoutRouteWithChildren,
  storecreateRoute: storecreateRoute,
  storedashboardRoute: storedashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth-layout-id",
        "/create-store",
        "/store/$storeId/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth-layout-id": {
      "filePath": "auth\\layout.tsx",
      "children": [
        "/_auth-layout-id/sign-in",
        "/_auth-layout-id/sign-up"
      ]
    },
    "/create-store": {
      "filePath": "store\\create.tsx"
    },
    "/_auth-layout-id/sign-in": {
      "filePath": "auth\\sign-in.tsx",
      "parent": "/_auth-layout-id"
    },
    "/_auth-layout-id/sign-up": {
      "filePath": "auth\\sign-up.tsx",
      "parent": "/_auth-layout-id"
    },
    "/store/$storeId/dashboard": {
      "filePath": "store\\dashboard.tsx",
      "children": [
        "/store/$storeId/dashboard/"
      ]
    },
    "/store/$storeId/dashboard/": {
      "filePath": "store\\dashboard-index.tsx",
      "parent": "/store/$storeId/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
