/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as storecreateImport } from './routes/store/create'
import { Route as authlayoutImport } from './routes/auth/layout'
import { Route as indexImport } from './routes/index'
import { Route as authsignUpImport } from './routes/auth/sign-up'
import { Route as authsignInImport } from './routes/auth/sign-in'
import { Route as storedashboardImport } from './routes/store/dashboard'
import { Route as storeproductsImport } from './routes/store/products'
import { Route as storeordersImport } from './routes/store/orders'
import { Route as storediscountsImport } from './routes/store/discounts'
import { Route as storecustomersImport } from './routes/store/customers'
import { Route as storedashboardIndexImport } from './routes/store/dashboard-index'
import { Route as storeproductNewImport } from './routes/store/product-new'
import { Route as storeproductsIndexImport } from './routes/store/products-index'

// Create/Update Routes

const storecreateRoute = storecreateImport.update({
  path: '/create-store',
  getParentRoute: () => rootRoute,
} as any)

const authlayoutRoute = authlayoutImport.update({
  id: '/_auth-layout-id',
  getParentRoute: () => rootRoute,
} as any)

const indexRoute = indexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authsignUpRoute = authsignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => authlayoutRoute,
} as any)

const authsignInRoute = authsignInImport.update({
  path: '/sign-in',
  getParentRoute: () => authlayoutRoute,
} as any)

const storedashboardRoute = storedashboardImport.update({
  path: '/store/$storeId/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const storeproductsRoute = storeproductsImport.update({
  path: '/products',
  getParentRoute: () => storedashboardRoute,
} as any)

const storeordersRoute = storeordersImport.update({
  path: '/orders',
  getParentRoute: () => storedashboardRoute,
} as any)

const storediscountsRoute = storediscountsImport.update({
  path: '/discounts',
  getParentRoute: () => storedashboardRoute,
} as any)

const storecustomersRoute = storecustomersImport.update({
  path: '/customers',
  getParentRoute: () => storedashboardRoute,
} as any)

const storedashboardIndexRoute = storedashboardIndexImport.update({
  path: '/',
  getParentRoute: () => storedashboardRoute,
} as any)

const storeproductNewRoute = storeproductNewImport.update({
  path: '/new',
  getParentRoute: () => storeproductsRoute,
} as any)

const storeproductsIndexRoute = storeproductsIndexImport.update({
  path: '/',
  getParentRoute: () => storeproductsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout-id': {
      id: '/_auth-layout-id'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authlayoutImport
      parentRoute: typeof rootRoute
    }
    '/create-store': {
      id: '/create-store'
      path: '/create-store'
      fullPath: '/create-store'
      preLoaderRoute: typeof storecreateImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout-id/sign-in': {
      id: '/_auth-layout-id/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authsignInImport
      parentRoute: typeof authlayoutImport
    }
    '/_auth-layout-id/sign-up': {
      id: '/_auth-layout-id/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authsignUpImport
      parentRoute: typeof authlayoutImport
    }
    '/store/$storeId/dashboard': {
      id: '/store/$storeId/dashboard'
      path: '/store/$storeId/dashboard'
      fullPath: '/store/$storeId/dashboard'
      preLoaderRoute: typeof storedashboardImport
      parentRoute: typeof rootRoute
    }
    '/store/$storeId/dashboard/': {
      id: '/store/$storeId/dashboard/'
      path: '/'
      fullPath: '/store/$storeId/dashboard/'
      preLoaderRoute: typeof storedashboardIndexImport
      parentRoute: typeof storedashboardImport
    }
    '/store/$storeId/dashboard/customers': {
      id: '/store/$storeId/dashboard/customers'
      path: '/customers'
      fullPath: '/store/$storeId/dashboard/customers'
      preLoaderRoute: typeof storecustomersImport
      parentRoute: typeof storedashboardImport
    }
    '/store/$storeId/dashboard/discounts': {
      id: '/store/$storeId/dashboard/discounts'
      path: '/discounts'
      fullPath: '/store/$storeId/dashboard/discounts'
      preLoaderRoute: typeof storediscountsImport
      parentRoute: typeof storedashboardImport
    }
    '/store/$storeId/dashboard/orders': {
      id: '/store/$storeId/dashboard/orders'
      path: '/orders'
      fullPath: '/store/$storeId/dashboard/orders'
      preLoaderRoute: typeof storeordersImport
      parentRoute: typeof storedashboardImport
    }
    '/store/$storeId/dashboard/products': {
      id: '/store/$storeId/dashboard/products'
      path: '/products'
      fullPath: '/store/$storeId/dashboard/products'
      preLoaderRoute: typeof storeproductsImport
      parentRoute: typeof storedashboardImport
    }
    '/store/$storeId/dashboard/products/': {
      id: '/store/$storeId/dashboard/products/'
      path: '/'
      fullPath: '/store/$storeId/dashboard/products/'
      preLoaderRoute: typeof storeproductsIndexImport
      parentRoute: typeof storeproductsImport
    }
    '/store/$storeId/dashboard/products/new': {
      id: '/store/$storeId/dashboard/products/new'
      path: '/new'
      fullPath: '/store/$storeId/dashboard/products/new'
      preLoaderRoute: typeof storeproductNewImport
      parentRoute: typeof storeproductsImport
    }
  }
}

// Create and export the route tree

interface authlayoutRouteChildren {
  authsignInRoute: typeof authsignInRoute
  authsignUpRoute: typeof authsignUpRoute
}

const authlayoutRouteChildren: authlayoutRouteChildren = {
  authsignInRoute: authsignInRoute,
  authsignUpRoute: authsignUpRoute,
}

const authlayoutRouteWithChildren = authlayoutRoute._addFileChildren(
  authlayoutRouteChildren,
)

interface storeproductsRouteChildren {
  storeproductsIndexRoute: typeof storeproductsIndexRoute
  storeproductNewRoute: typeof storeproductNewRoute
}

const storeproductsRouteChildren: storeproductsRouteChildren = {
  storeproductsIndexRoute: storeproductsIndexRoute,
  storeproductNewRoute: storeproductNewRoute,
}

const storeproductsRouteWithChildren = storeproductsRoute._addFileChildren(
  storeproductsRouteChildren,
)

interface storedashboardRouteChildren {
  storedashboardIndexRoute: typeof storedashboardIndexRoute
  storecustomersRoute: typeof storecustomersRoute
  storediscountsRoute: typeof storediscountsRoute
  storeordersRoute: typeof storeordersRoute
  storeproductsRoute: typeof storeproductsRouteWithChildren
}

const storedashboardRouteChildren: storedashboardRouteChildren = {
  storedashboardIndexRoute: storedashboardIndexRoute,
  storecustomersRoute: storecustomersRoute,
  storediscountsRoute: storediscountsRoute,
  storeordersRoute: storeordersRoute,
  storeproductsRoute: storeproductsRouteWithChildren,
}

const storedashboardRouteWithChildren = storedashboardRoute._addFileChildren(
  storedashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '': typeof authlayoutRouteWithChildren
  '/create-store': typeof storecreateRoute
  '/sign-in': typeof authsignInRoute
  '/sign-up': typeof authsignUpRoute
  '/store/$storeId/dashboard': typeof storedashboardRouteWithChildren
  '/store/$storeId/dashboard/': typeof storedashboardIndexRoute
  '/store/$storeId/dashboard/customers': typeof storecustomersRoute
  '/store/$storeId/dashboard/discounts': typeof storediscountsRoute
  '/store/$storeId/dashboard/orders': typeof storeordersRoute
  '/store/$storeId/dashboard/products': typeof storeproductsRouteWithChildren
  '/store/$storeId/dashboard/products/': typeof storeproductsIndexRoute
  '/store/$storeId/dashboard/products/new': typeof storeproductNewRoute
}

export interface FileRoutesByTo {
  '/': typeof indexRoute
  '': typeof authlayoutRouteWithChildren
  '/create-store': typeof storecreateRoute
  '/sign-in': typeof authsignInRoute
  '/sign-up': typeof authsignUpRoute
  '/store/$storeId/dashboard': typeof storedashboardIndexRoute
  '/store/$storeId/dashboard/customers': typeof storecustomersRoute
  '/store/$storeId/dashboard/discounts': typeof storediscountsRoute
  '/store/$storeId/dashboard/orders': typeof storeordersRoute
  '/store/$storeId/dashboard/products': typeof storeproductsIndexRoute
  '/store/$storeId/dashboard/products/new': typeof storeproductNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof indexRoute
  '/_auth-layout-id': typeof authlayoutRouteWithChildren
  '/create-store': typeof storecreateRoute
  '/_auth-layout-id/sign-in': typeof authsignInRoute
  '/_auth-layout-id/sign-up': typeof authsignUpRoute
  '/store/$storeId/dashboard': typeof storedashboardRouteWithChildren
  '/store/$storeId/dashboard/': typeof storedashboardIndexRoute
  '/store/$storeId/dashboard/customers': typeof storecustomersRoute
  '/store/$storeId/dashboard/discounts': typeof storediscountsRoute
  '/store/$storeId/dashboard/orders': typeof storeordersRoute
  '/store/$storeId/dashboard/products': typeof storeproductsRouteWithChildren
  '/store/$storeId/dashboard/products/': typeof storeproductsIndexRoute
  '/store/$storeId/dashboard/products/new': typeof storeproductNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/create-store'
    | '/sign-in'
    | '/sign-up'
    | '/store/$storeId/dashboard'
    | '/store/$storeId/dashboard/'
    | '/store/$storeId/dashboard/customers'
    | '/store/$storeId/dashboard/discounts'
    | '/store/$storeId/dashboard/orders'
    | '/store/$storeId/dashboard/products'
    | '/store/$storeId/dashboard/products/'
    | '/store/$storeId/dashboard/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/create-store'
    | '/sign-in'
    | '/sign-up'
    | '/store/$storeId/dashboard'
    | '/store/$storeId/dashboard/customers'
    | '/store/$storeId/dashboard/discounts'
    | '/store/$storeId/dashboard/orders'
    | '/store/$storeId/dashboard/products'
    | '/store/$storeId/dashboard/products/new'
  id:
    | '__root__'
    | '/'
    | '/_auth-layout-id'
    | '/create-store'
    | '/_auth-layout-id/sign-in'
    | '/_auth-layout-id/sign-up'
    | '/store/$storeId/dashboard'
    | '/store/$storeId/dashboard/'
    | '/store/$storeId/dashboard/customers'
    | '/store/$storeId/dashboard/discounts'
    | '/store/$storeId/dashboard/orders'
    | '/store/$storeId/dashboard/products'
    | '/store/$storeId/dashboard/products/'
    | '/store/$storeId/dashboard/products/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  authlayoutRoute: typeof authlayoutRouteWithChildren
  storecreateRoute: typeof storecreateRoute
  storedashboardRoute: typeof storedashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  authlayoutRoute: authlayoutRouteWithChildren,
  storecreateRoute: storecreateRoute,
  storedashboardRoute: storedashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth-layout-id",
        "/create-store",
        "/store/$storeId/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth-layout-id": {
      "filePath": "auth\\layout.tsx",
      "children": [
        "/_auth-layout-id/sign-in",
        "/_auth-layout-id/sign-up"
      ]
    },
    "/create-store": {
      "filePath": "store\\create.tsx"
    },
    "/_auth-layout-id/sign-in": {
      "filePath": "auth\\sign-in.tsx",
      "parent": "/_auth-layout-id"
    },
    "/_auth-layout-id/sign-up": {
      "filePath": "auth\\sign-up.tsx",
      "parent": "/_auth-layout-id"
    },
    "/store/$storeId/dashboard": {
      "filePath": "store\\dashboard.tsx",
      "children": [
        "/store/$storeId/dashboard/",
        "/store/$storeId/dashboard/customers",
        "/store/$storeId/dashboard/discounts",
        "/store/$storeId/dashboard/orders",
        "/store/$storeId/dashboard/products"
      ]
    },
    "/store/$storeId/dashboard/": {
      "filePath": "store\\dashboard-index.tsx",
      "parent": "/store/$storeId/dashboard"
    },
    "/store/$storeId/dashboard/customers": {
      "filePath": "store\\customers.tsx",
      "parent": "/store/$storeId/dashboard"
    },
    "/store/$storeId/dashboard/discounts": {
      "filePath": "store\\discounts.tsx",
      "parent": "/store/$storeId/dashboard"
    },
    "/store/$storeId/dashboard/orders": {
      "filePath": "store\\orders.tsx",
      "parent": "/store/$storeId/dashboard"
    },
    "/store/$storeId/dashboard/products": {
      "filePath": "store\\products.tsx",
      "parent": "/store/$storeId/dashboard",
      "children": [
        "/store/$storeId/dashboard/products/",
        "/store/$storeId/dashboard/products/new"
      ]
    },
    "/store/$storeId/dashboard/products/": {
      "filePath": "store\\products-index.tsx",
      "parent": "/store/$storeId/dashboard/products"
    },
    "/store/$storeId/dashboard/products/new": {
      "filePath": "store\\product-new.tsx",
      "parent": "/store/$storeId/dashboard/products"
    }
  }
}
ROUTE_MANIFEST_END */
