/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authlayoutImport } from './routes/auth/layout'
import { Route as indexImport } from './routes/index'
import { Route as authsignUpImport } from './routes/auth/sign-up'
import { Route as authsignInImport } from './routes/auth/sign-in'

// Create/Update Routes

const authlayoutRoute = authlayoutImport.update({
  id: '/_auth-layout-id',
  getParentRoute: () => rootRoute,
} as any)

const indexRoute = indexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authsignUpRoute = authsignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => authlayoutRoute,
} as any)

const authsignInRoute = authsignInImport.update({
  path: '/sign-in',
  getParentRoute: () => authlayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout-id': {
      id: '/_auth-layout-id'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authlayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout-id/sign-in': {
      id: '/_auth-layout-id/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authsignInImport
      parentRoute: typeof authlayoutImport
    }
    '/_auth-layout-id/sign-up': {
      id: '/_auth-layout-id/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authsignUpImport
      parentRoute: typeof authlayoutImport
    }
  }
}

// Create and export the route tree

interface authlayoutRouteChildren {
  authsignInRoute: typeof authsignInRoute
  authsignUpRoute: typeof authsignUpRoute
}

const authlayoutRouteChildren: authlayoutRouteChildren = {
  authsignInRoute: authsignInRoute,
  authsignUpRoute: authsignUpRoute,
}

const authlayoutRouteWithChildren = authlayoutRoute._addFileChildren(
  authlayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '': typeof authlayoutRouteWithChildren
  '/sign-in': typeof authsignInRoute
  '/sign-up': typeof authsignUpRoute
}

export interface FileRoutesByTo {
  '/': typeof indexRoute
  '': typeof authlayoutRouteWithChildren
  '/sign-in': typeof authsignInRoute
  '/sign-up': typeof authsignUpRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof indexRoute
  '/_auth-layout-id': typeof authlayoutRouteWithChildren
  '/_auth-layout-id/sign-in': typeof authsignInRoute
  '/_auth-layout-id/sign-up': typeof authsignUpRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/sign-in' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_auth-layout-id'
    | '/_auth-layout-id/sign-in'
    | '/_auth-layout-id/sign-up'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  authlayoutRoute: typeof authlayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  authlayoutRoute: authlayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth-layout-id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth-layout-id": {
      "filePath": "auth\\layout.tsx",
      "children": [
        "/_auth-layout-id/sign-in",
        "/_auth-layout-id/sign-up"
      ]
    },
    "/_auth-layout-id/sign-in": {
      "filePath": "auth\\sign-in.tsx",
      "parent": "/_auth-layout-id"
    },
    "/_auth-layout-id/sign-up": {
      "filePath": "auth\\sign-up.tsx",
      "parent": "/_auth-layout-id"
    }
  }
}
ROUTE_MANIFEST_END */
